# -*- coding: utf-8 -*-
"""day10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hL62foGJ0g4PO969WcCMp29n3rBqPDwD
"""

'''Assignment 1: Sorting and Ranking Data
Tasks:
Sort the dataset by Account_Balance in descending order and display the first 10 rows.
Create a ranking column for Transaction_Amount within each Branch:
Use rank() to give ranks for transactions based on their amounts within each branch.
Objective:
Learn how to sort data and apply ranking based on certain columns.
'''

import pandas as pd

# Load your dataset (replace with actual file path)
df = pd.read_csv('Day_9_banking_data.csv')

# 1. Sort by Account_Balance in descending order and display the first 10 rows
sorted_df = df.sort_values(by='Account_Balance', ascending=False)
print("Sorted by Account_Balance (Top 10 rows):")
print(sorted_df.head(10))

# 2. Create a ranking column for Transaction_Amount within each Branch
df['Transaction_Rank'] = df.groupby('Branch')['Transaction_Amount'].rank(ascending=False)

# Display the dataframe with the new ranking column
print("\nData with Transaction Rank within Branches:")
print(df.head())  # This displays the top rows of the dataframe with the new column