# -*- coding: utf-8 -*-
"""day7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hL62foGJ0g4PO969WcCMp29n3rBqPDwD
"""

'''
Load and Explore the Data
Load the sales_data.csv file using Pandas.
Display the first 5 rows of the dataset.
Print basic statistics (mean, median, min, max, etc.) of the numerical columns using .describe().'''

import pandas as p

# Load the sales_data.csv fidle
df = pd.read_csv('Day_7_sales_data.csv')

# Display the first 5 rows of the dataset
print("First 5 rows of the dataset:")
print(df.head())

# Print basic statistics (mean, median, min, max, etc.) of the numerical columns
print("\nBasic statistics of the numerical columns:")
print(df.describe())

'''Data Analysis
Calculate the total sales for each region.
Find the most sold product (based on quantity).
Compute the average profit margin for each product. (Profit margin = Profit / Sales * 100)'''

# Load the sales_data.csv file
df = pd.read_csv('Day_7_sales_data.csv')

# 1. Calculate the total sales for each region
total_sales_by_region = df.groupby('Region')['Sales'].sum()

# Display total sales by region
print("Total Sales for each region:")
print(total_sales_by_region)

# 2. Find the most sold product based on quantity
most_sold_product = df.groupby('Product')['Quantity'].sum().idxmax()

# Display the most sold product
print(f"\nThe most sold product based on quantity: {most_sold_product}")

# 3. Compute the average profit margin for each product
# First, create a new column for profit margin
df['Profit_Margin'] = (df['Profit'] / df['Sales']) * 100

# Now, calculate the average profit margin for each product
average_profit_margin = df.groupby('Product')['Profit_Margin'].mean()

# Display the average profit margin for each product
print("\nAverage profit margin for each product:")
print(average_profit_margin)