# -*- coding: utf-8 -*-
"""day9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hL62foGJ0g4PO969WcCMp29n3rBqPDwD
"""

'''Assignment 1: Data Exploration
Tasks:
Load the banking_data.csv file using Pandas.
Display the first 5 rows of the dataset.
Use .describe() to generate basic statistics of the numerical columns (e.g., Transaction_Amount, Account_Balance).
Check for missing values in the dataset.
Objective:
Understand how to load and inspect the dataset.
Use basic descriptive statistics and data integrity checks.'''

import pandas as pd

# Load the banking_data.csv file
df = pd.read_csv('Day_9_banking_data.csv')

# 1. Display the first 5 rows of the dataset
print("First 5 rows of the dataset:")
print(df.head())

# 2. Generate basic statistics of the numerical columns (e.g., Transaction_Amount, Account_Balance)
print("\nBasic statistics of the numerical columns:")
print(df.describe())

# 3. Check for missing values in the dataset
print("\nCheck for missing values:")
print(df.isnull().sum())

'''Assignment 2: Data Aggregation and Grouping
Tasks:
Group the data by Account_Type and calculate:
The total sum of Transaction_Amount.
The average Account_Balance for each account type.
Group the data by Branch and calculate:
The total number of transactions per branch.
The average transaction amount per branch.
Objective:
Learn to use groupby() for aggregating data by categories.
Gain skills in calculating grouped statistics.
'''

import pandas as pd

# Load the banking_data.csv file
df = pd.read_csv('Day_9_banking_data.csv')

# 1. Group the data by Account_Type and calculate:
# a. The total sum of Transaction_Amount for each Account_Type
transaction_sum_by_account_type = df.groupby('Account_Type')['Transaction_Amount'].sum()

# b. The average Account_Balance for each Account_Type
average_balance_by_account_type = df.groupby('Account_Type')['Account_Balance'].mean()

# Display the results for Account_Type
print("Total sum of Transaction_Amount and average Account_Balance by Account_Type:")
print(transaction_sum_by_account_type)
print(average_balance_by_account_type)

# 2. Group the data by Branch and calculate:
# a. The total number of transactions per Branch
transaction_count_by_branch = df.groupby('Branch')['Transaction_Amount'].count()

# b. The average transaction amount per Branch
average_transaction_amount_by_branch = df.groupby('Branch')['Transaction_Amount'].mean()

# Display the results for Branch
print("\nTotal number of transactions and average transaction amount by Branch:")
print(transaction_count_by_branch)
print(average_transaction_amount_by_branch)